
export function formatScanReport(scanResult: any) {
  const header = `ANTIGINX SECURITY SCAN REPORT\n${'='.repeat(50)}\n\n`;
  const info = `Target URL: ${scanResult.target_url}\n`;
  const status = `Status: ${scanResult.status}\n`;
  const created = `Scan Date: ${new Date(scanResult.created_at).toLocaleString()}\n`;
  const completed = scanResult.completed_at ? `Completed: ${new Date(scanResult.completed_at).toLocaleString()}\n` : '';
  const separator = `\n${'='.repeat(50)}\n\n`;

  const testsHeader = `TEST RESULTS (${scanResult.results.length} total)\n${'-'.repeat(50)}\n\n`;

  const tests = scanResult.results.map((result: any, idx: number) => {
    const cleanMessage = result.message.replace(/[\u0000-\u001F\u007F-\u009F]/g, '').trim();
    const message = cleanMessage.charAt(0).toUpperCase() + cleanMessage.slice(1);

    return `${idx + 1}. ${result.test_name}\n` +
           `   Status: ${result.passed ? '✓ PASSED' : '✗ FAILED'}\n` +
           `   Severity: ${result.severity}\n` +
           `   Message: ${message}\n`;
  }).join('\n');

  const footer = `\n${'='.repeat(50)}\n` +
               `Report generated by Antiginx Security Scanner\n` +
               `${new Date().toLocaleString()}`;

  return header + info + status + created + completed + separator + testsHeader + tests + footer;
}

export function downloadScanReport(scanResult: any) {
  const report = formatScanReport(scanResult);
  const blob = new Blob([report], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `antiginx-scan-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default { formatScanReport, downloadScanReport };
