"use client";

import { ScanResponse } from '@/app/lib/api';
import ScanResultItem from './ScanResultItem';

interface ScanResultModalProps {
  isOpen: boolean;
  onClose: () => void;
  scanResult: ScanResponse;
}

export default function ScanResultModal({ isOpen, onClose, scanResult }: ScanResultModalProps) {
  if (!isOpen) return null;

  const handleExport = () => {
    const formatReport = () => {
      const header = `ANTIGINX SECURITY SCAN REPORT\n${'='.repeat(50)}\n\n`;
      const info = `Target URL: ${scanResult.target_url}\n`;
      const status = `Status: ${scanResult.status}\n`;
      const created = `Scan Date: ${new Date(scanResult.created_at).toLocaleString()}\n`;
      const completed = scanResult.completed_at ? `Completed: ${new Date(scanResult.completed_at).toLocaleString()}\n` : '';
      const separator = `\n${'='.repeat(50)}\n\n`;
      
      const testsHeader = `TEST RESULTS (${scanResult.results.length} total)\n${'-'.repeat(50)}\n\n`;
      
      const tests = scanResult.results.map((result, idx) => {
        const cleanMessage = result.message.replace(/[\u0000-\u001F\u007F-\u009F]/g, '').trim();
        const message = cleanMessage.charAt(0).toUpperCase() + cleanMessage.slice(1);
        
        return `${idx + 1}. ${result.test_name}\n` +
               `   Status: ${result.passed ? '✓ PASSED' : '✗ FAILED'}\n` +
               `   Severity: ${result.severity}\n` +
               `   Message: ${message}\n`;
      }).join('\n');
      
      const footer = `\n${'='.repeat(50)}\n` +
                   `Report generated by Antiginx Security Scanner\n` +
                   `${new Date().toLocaleString()}`;
      
      return header + info + status + created + completed + separator + testsHeader + tests + footer;
    };
    
    const report = formatReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `antiginx-scan-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const sortedResults = [...scanResult.results].sort((a, b) => {
    const severityOrder = { 'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3, 'INFO': 4 };
    const aOrder = severityOrder[a.severity.toUpperCase() as keyof typeof severityOrder] ?? 5;
    const bOrder = severityOrder[b.severity.toUpperCase() as keyof typeof severityOrder] ?? 5;
    return aOrder - bOrder;
  }).map((result, index) => ({ ...result, animIndex: index }));

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div 
        className="bg-black/60 backdrop-blur-xl rounded-lg shadow-[0_0_30px_rgba(6,182,212,0.15)] border border-cyan-500/30 max-w-2xl w-full max-h-[85vh] overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="px-5 py-3 border-b border-cyan-500/20">
          <div className="flex items-center justify-between">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <h2 className="text-base font-bold text-white">Security Scan Results</h2>
              </div>
              <div className="flex items-center gap-2 text-xs">
                <i className="ri-global-line text-zinc-500"></i>
                <span className="text-cyan-400/80 font-mono truncate">{scanResult.target_url.replace(/^https?:\/\//, '')}</span>
                <span className={`px-2 py-0.5 rounded text-xs font-medium flex items-center gap-1 ${
                  scanResult.status === 'COMPLETED' ? 'bg-green-500/15 text-green-400' :
                  scanResult.status === 'RUNNING' ? 'bg-yellow-500/15 text-yellow-400' :
                  scanResult.status === 'FAILED' ? 'bg-red-500/15 text-red-400' :
                  'bg-zinc-600/15 text-zinc-400'
                }`}>
                  {scanResult.status === 'COMPLETED' && <i className="ri-checkbox-circle-fill text-[10px]"></i>}
                  {scanResult.status === 'RUNNING' && <i className="ri-loader-4-line animate-spin text-[10px]"></i>}
                  {scanResult.status === 'FAILED' && <i className="ri-error-warning-fill text-[10px]"></i>}
                  {scanResult.status}
                </span>
              </div>
            </div>
            <button 
              onClick={onClose}
              className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-zinc-800/50 transition-colors cursor-pointer group ml-3"
            >
              <i className="ri-close-line text-lg text-zinc-400 group-hover:text-white transition-colors"></i>
            </button>
          </div>
        </div>
        
        {/* Modal Content */}
        <div className="p-4 overflow-y-auto max-h-[calc(85vh-120px)]">
          {scanResult.results.length === 0 ? (
            <div className="text-center py-8">
              <div className="inline-flex items-center justify-center w-12 h-12 mb-2">
                <div className="animate-spin rounded-full h-12 w-12 border-4 border-cyan-500 border-t-transparent"></div>
              </div>
              <h3 className="text-sm font-semibold text-white mb-1">Scanning in Progress</h3>
              <p className="text-zinc-400 text-sm">Analyzing website security...</p>
            </div>
          ) : (
            <div className="space-y-2.5">
              {sortedResults.map((result) => (
                <ScanResultItem key={result.id} result={result} index={result.animIndex} />
              ))}
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-5 py-3 border-t border-zinc-800/50 flex items-center justify-between">
          <div className="text-xs text-zinc-400 hidden lg:flex items-center gap-3">
            {scanResult.results.length > 0 && (
              <span>{scanResult.results.length} test{scanResult.results.length !== 1 ? 's' : ''} completed</span>
            )}
          </div>
          <div className="flex items-center gap-2.5 ml-auto">
            {scanResult.results.length > 0 && (
              <button 
                onClick={handleExport}
                className="px-3.5 py-1.5 bg-cyan-600/20 text-cyan-300 rounded-lg hover:bg-cyan-600/30 transition-all font-medium text-xs border border-cyan-500/30 cursor-pointer flex items-center gap-1.5"
              >
                <i className="ri-download-line text-sm"></i>
                Export
              </button>
            )}
            <button 
              onClick={onClose}
              className="px-4 py-2 bg-zinc-800/50 text-zinc-300 rounded-lg hover:bg-zinc-700/50 transition-all font-medium text-sm border border-zinc-700/50 cursor-pointer"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
