name: Security Verification
run-name: >-
    ${{ 
        github.event_name == 'pull_request' 
        && format('Security Verification for CI: PR #{0} -> {1}', github.event.number, github.event.pull_request.title)
        ||
        github.event_name == 'push'
        && format('Security Verification for CI: Merge -> {0}', github.event.head_commit.message)
    }}

on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches: [ "main" ]

permissions:
    contents: read

concurrency:
    group: ${{ github.event_name == 'pull_request' && format('{0}-pr-{1}', github.workflow, github.event.pull_request.number) || format('{0}-ref-{1}', github.workflow, github.ref) }}
    cancel-in-progress: true

jobs:
    security-ci-test:
        name: Testing
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
        - name: 📥 Git -- Checkout repository
          uses: actions/checkout@v6

        - name: 📘 Node -- Set up
          uses: actions/setup-node@v3
          with:
            node-version: '22'
            cache: npm

        - name: 📦 Node -- Install dependencies
          run: npm ci

        - name: 🧪 Node -- Test Vulnerability -> Modules
          run: | 
            echo "⚙️ Running npm audit on Node modules:"
            if npm audit --audit-level=moderate; then
                echo ""
                echo "✅ No vulnerabilities found in Node modules."
            else
                echo ""
                echo "❌ Vulnerabilities found in Node modules."
                exit 1
            fi

        - name: 🧪 Trivy -- Test Vuln, Secret, Misconfig -> File System
          uses: aquasecurity/trivy-action@0.35.0
          with:
            scan-type: fs
            scan-ref: .
            ignore-unfixed: true
            scanners: vuln,secret,misconfig
            format: table
            severity: CRITICAL,HIGH,MEDIUM
            exit-code: '1'